from fastapi import APIRouter, Depends, Request
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.database.connection import get_db
from app.dependencies.auth import get_current_user
from app.models.auth import User
from app.schemas.base import StandardResponse
from app.schemas.ai import ChatRequest, StudyPlanRequest, ResumeReviewRequest
from app.agents.supervisor import mentor_graph
from app.memory.redis_memory import MemoryManager
from langchain_core.messages import HumanMessage
import json
import asyncio

router = APIRouter(prefix="/ai", tags=["AI Mentor"])

@router.post("/chat")
async def chat_with_mentor(request: ChatRequest, current_user: User = Depends(get_current_user)):
    """
    General chat endpoint utilizing the Multi-Agent LangGraph.
    Streams the response using Server-Sent Events (SSE).
    """
    # 1. Retrieve Memory
    session_id = request.session_id or f"session_{current_user.id}"
    history = MemoryManager.get_session_history(session_id)
    
    # 2. Add current message
    history.add_user_message(request.message)
    
    async def event_stream():
        try:
            # Note: For true token streaming, we'd use astream_events. 
            # For simplicity in this scaffold, we'll stream the graph node updates.
            async for output in mentor_graph.astream({"messages": history.messages}):
                for node_name, state in output.items():
                    if "messages" in state:
                        # Get the latest message generated by the node
                        latest_msg = state["messages"][-1].content
                        yield f"data: {json.dumps({'chunk': latest_msg, 'node': node_name})}\n\n"
                        # Save to memory
                        history.add_ai_message(latest_msg)
                        
            yield "data: [DONE]\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    if request.stream:
        return StreamingResponse(event_stream(), media_type="text/event-stream")
    else:
        # Non-streaming fallback
        result = await mentor_graph.ainvoke({"messages": history.messages})
        final_msg = result["messages"][-1].content
        history.add_ai_message(final_msg)
        return StandardResponse(success=True, message="Success", data={"response": final_msg})

@router.post("/study-plan", response_model=StandardResponse)
def generate_study_plan(request: StudyPlanRequest, current_user: User = Depends(get_current_user)):
    # Direct execution of Career Agent logic
    return StandardResponse(success=True, message="Study plan generated (Placeholder)", data={})

@router.post("/resume-review", response_model=StandardResponse)
def review_resume(request: ResumeReviewRequest, current_user: User = Depends(get_current_user)):
    # Direct execution of Resume Agent logic
    return StandardResponse(success=True, message="Resume reviewed (Placeholder)", data={})

@router.get("/history", response_model=StandardResponse)
def get_chat_history(session_id: str, current_user: User = Depends(get_current_user)):
    history = MemoryManager.get_session_history(session_id)
    messages = [{"role": m.type, "content": m.content} for m in history.messages]
    return StandardResponse(success=True, message="History retrieved", data=messages)
